id: P27472E7F
initial_creation_type: input
source_metadata:
  title: Gatön Ngawang Lekpa Series
  language: bo
  description: 'Texts by and about the Sakya lama Gatön Ngawang Lekpa (sga ston ngag
    dbang legs pa, 1867–1941) of Tharlam Monastery, one of the foremost Lamdré (lam
    ’bras) teachers of recent times:'
  volume:
    922a2f2649d5404693bad74fb78d0975:
      title: 'Ocean of Offering Clouds: A Light Offering Prayer'
      parent: Aspiration Prayers
    f4571468dbf8400b9cec1a5beb7ca4ab:
      title: 'The Heart of the Mahāyāna Path: A Bodhisattva’s Prayer of Aspiration'
      parent: Aspiration Prayers
    2d0eb965977545f0b7f0fb2994ab0497:
      title: Supplement to the Lineage Prayer for the Lamdré Instructions Composed
        by Tsarchen
      parent: Lineage Prayers
    fe5395f47b1a471e912da2e56ea00174:
      title: Aspiration for the Long Life of Dezhung Rinpoche (Jampa Kunga Tenpé Nyima)
      parent: Long Life Prayers
    5b101e8e20c6462a931ecd72d681fa9c:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
      parent: Long Life Prayers
    19568fd162294e878596b9ddde58d874:
      title: Prayer for the Long Life of Khyenrab Chökyi Özer
      parent: Long Life Prayers
    9e8941634ff84a5d8e9b279f00680c5e:
      title: 'Cloud Banks of Blessings: Praise and Prayer to the Vajradhara Ngawang
        Lekpa'
      parent: Praise
    9b143de4d2c34e64ac276766d6581275:
      title: Praise of Kunga Yeshe, Great Being and Master of Extensive Scriptural
        Traditions
      parent: Praise
created_at: '2022-02-28T23:22:34.050503'
last_modified_at: '2022-02-28T23:22:34.050506'
statistics:
  total_words: 2336
  total_non_words: 215
quality:
  non_words_ratio: 0.09
